### ISSUE TITLE
Request parse error brings down plugin

### ISSUE THREAD

**Issue by bracki** [winebarrel/fluent-plugin-elb-access-log#1]
```
2015-06-01 19:10:53 +0000 [info]: plugin/out_elasticsearch.rb:67:client: Connection opened to Elasticsearch cluster => {:host=>"localhost", :port=>9200, :scheme=>"http"}
2015-06-01 19:12:25 +0000 [warn]: plugin/in_elb_access_log.rb:228:rescue in parse_request!: undefined method `scheme' for nil:NilClass:
2015-06-01 19:12:25 +0000 [error]: plugin/in_elb_access_log.rb:284:rescue in on_timer: undefined method `split' for nil:NilClass
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:208:in `split_address_port!'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:172:in `block in emit_access_log'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:165:in `each'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:165:in `emit_access_log'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:133:in `block (3 levels) in fetch'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:123:in `each'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:123:in `block (2 levels) in fetch'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/aws-sdk-core/pageable_response.rb:77:in `each'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:122:in `block in fetch'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:121:in `each'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:121:in `fetch'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:86:in `block in start'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:282:in `call'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:282:in `on_timer'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2015-06-01 19:12:25 +0000 [error]: cool.io/loop.rb:88:run: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:112:in `run'
```
Once I see this the plugin basically stops. I guess it fails to parse a log line. Any ideas?

**Comment by winebarrel** [comment]
Sorry for replying late.
I will try to fix it.

Please tell me your enviromnet. (OS / td version etc...)

**Comment by winebarrel** [comment]
I've fixed the bug.
Please try v0.3.0 :smiley:
