### ISSUE TITLE
Error occurs when are using the AWS SDK 2.1.1

### ISSUE THREAD

**Issue by katsuhiko** [winebarrel/fluent-plugin-elb-access-log#2]
td-agent 0.12.7
aws-sdk (2.1.1)
aws-sdk-core (2.1.1)
aws-sdk-resources (2.1.1)
fluent-plugin-elb-access-log (0.2.4)

```
2015-06-21 03:09:02 +0000 [error]: undefined method `each' for #<Aws::S3::Types::GetObjectOutput:0x007f37723d8668>
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/response.rb:79:in `first'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.1/lib/seahorse/client/response.rb:79:in `method_missing'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:132:in `block (3 levels) in fetch'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:123:in `each'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:123:in `block (2 levels) in fetch'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.1/lib/aws-sdk-core/pageable_response.rb:75:in `each'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:122:in `block in fetch'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:121:in `each'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:121:in `fetch'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:86:in `block in start'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:282:in `call'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:282:in `on_timer'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run_once'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.3.0/lib/cool.io/loop.rb:88:in `run'
  2015-06-21 03:09:02 +0000 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elb-access-log-0.2.4/lib/fluent/plugin/in_elb_access_log.rb:112:in `run'
```

**Comment by winebarrel** [comment]
Thanks!

**Comment by winebarrel** [comment]
I've fixed the bug.
Please try v0.3.0 :smiley:

**Comment by katsuhiko** [comment]
I tried v0.3.0.
Problem had been resolved.

Thanks!

**Comment by winebarrel** [comment]
:smiley:
